// BUILD_ID: 2026-07-03_post_merge_closeout_acceptance_reference_consistency_contract_v1
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";
const root=resolve(dirname(fileURLToPath(import.meta.url)),"..");
const read=(p)=>readFileSync(resolve(root,p),"utf8"); const json=(p)=>JSON.parse(read(p));
const base="tests/fixtures/post-merge-closeout-acceptance-reference-consistency-contract";
const paths={doc:"docs/orchestration/post_merge_closeout_acceptance_reference_consistency_contract.md",schema:"schema/orchestration/post_merge_closeout_acceptance_reference_consistency_contract.schema.json",test:"tests/post_merge_closeout_acceptance_reference_consistency_contract.test.mjs",valid:`${base}/valid/consistent-owner-accepted-closeout-reference.json`,missing:`${base}/invalid/accepted-status-without-owner-phrase.json`,closeout:`${base}/invalid/closeout-packet-sha-mismatch.json`,status:`${base}/invalid/final-lane-status-mismatch.json`,scout:`${base}/invalid/next-scout-source-mismatch.json`,runtime:`${base}/invalid/runtime-action-present-after-acceptance.json`};
const BUILD="2026-07-03_post_merge_closeout_acceptance_reference_consistency_contract_v1"; const sha=/^[A-Fa-f0-9]{64}$/;
function validate(r){const e=[];if(r.build_id!==BUILD)e.push("build_id");if(r.lane_id!=="POST_MERGE_CLOSEOUT_EVIDENCE_CONSISTENCY_CONTRACT")e.push("lane_id");if(r.owner_acceptance!=="OWNER_ACCEPT_PR_11_LANE_CLOSED_MERGED_NO_RUNTIME_ACTION")e.push("owner_acceptance");if(r.final_lane_status!=="CLOSED_MERGED_NO_RUNTIME_ACTION")e.push("final_lane_status");if(!sha.test(r.closeout_packet?.sha256??"")||r.closeout_packet.sha256!=="28D92EE2E4405770EBF4CEEF081B9A7C9650C27AB245E98431942CF3E7EAB424")e.push("closeout_packet.sha256");if(r.closeout_packet?.classification!=="POST_MERGE_CLOSEOUT_EVIDENCE_CONSISTENCY_CONTRACT_PR_11_POST_MERGE_CLOSEOUT_READY"||r.closeout_packet?.blocker_matrix!=="NO_BLOCKERS")e.push("closeout identity");if(r.pr?.number!==11||r.pr?.state!=="MERGED"||r.pr?.merged_at!=="2026-07-02T10:10:33Z")e.push("pr");if(r.squash_commit!==r.remote_master||r.squash_commit!=="8934e5cd1370bb38a2ad062b2b45fa7048e301f2")e.push("merge commit");if(r.retained_branch?.name!=="post-submission/post-merge-closeout-evidence-consistency-contract"||r.retained_branch?.head!=="fb6f77fced275a7993a8d6ff66569d78cc0975cf")e.push("retained branch");if(r.next_scout?.sha256!=="9DEA33832710B29E01D3F57099E1C7752C6E3331590A5D3AD97F1F3A87E7C6FA"||r.next_scout?.source_lane_id!==r.lane_id||r.next_scout?.owner_acceptance!==r.owner_acceptance||r.next_scout?.primary_recommendation!=="POST_MERGE_CLOSEOUT_ACCEPTANCE_REFERENCE_CONSISTENCY_CONTRACT")e.push("next_scout");for(const [k,v] of Object.entries(r.safety_boundary??{}))if(v!==false)e.push(`safety.${k}`);return e;}
test("schema pins strict acceptance reference identity",()=>{const s=json(paths.schema);assert.equal(s.additionalProperties,false);assert.equal(s.properties.owner_acceptance.const,"OWNER_ACCEPT_PR_11_LANE_CLOSED_MERGED_NO_RUNTIME_ACTION");assert.equal(s.properties.pr.properties.number.const,11)});
test("consistent accepted reference passes",()=>assert.deepEqual(validate(json(paths.valid)),[]));
function mutated(p){const r=structuredClone(json(paths.valid));const m=json(p);const parts=m.path.split(".");let x=r;for(const part of parts.slice(0,-1))x=x[part];if(m.remove)delete x[parts.at(-1)];else x[parts.at(-1)]=m.value;return r;}
for(const [name,p,reason] of [["missing acceptance",paths.missing,"owner_acceptance"],["closeout SHA mismatch",paths.closeout,"closeout_packet.sha256"],["lane status mismatch",paths.status,"final_lane_status"],["scout source mismatch",paths.scout,"next_scout"],["runtime action",paths.runtime,"safety.runtime"]])test(`${name} fails closed`,()=>assert.ok(validate(mutated(p)).some(x=>x.includes(reason))));
test("docs distinguish evidence from acceptance reference",()=>{const d=read(paths.doc);assert.match(d,/earlier contract proves that closeout evidence agrees/);assert.match(d,/READY is not GO/)});
test("exact new file set is bounded",()=>assert.equal(Object.values(paths).length,9));
