// BUILD_ID: 2026-07-08_replacement_closeout_evidence_consistency_contract_v1
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";
const root=resolve(dirname(fileURLToPath(import.meta.url)),"..");
const read=(p)=>readFileSync(resolve(root,p),"utf8"); const json=(p)=>JSON.parse(read(p));
const base="tests/fixtures/replacement-closeout-evidence-consistency-contract";
const paths={doc:"docs/orchestration/replacement_closeout_evidence_consistency_contract.md",schema:"schema/orchestration/replacement_closeout_evidence_consistency_contract.schema.json",test:"tests/replacement_closeout_evidence_consistency_contract.test.mjs",valid:`${base}/valid/complete-closeout-chain.json`,missing:`${base}/invalid/missing-pr12-close-link.json`,branch:`${base}/invalid/branch-deletion-treated-as-default.json`};
const BUILD="2026-07-08_replacement_closeout_evidence_consistency_contract_v1"; const sha=/^[A-Fa-f0-9]{64}$/;
function validate(r){const e=[];if(r.build_id!==BUILD)e.push("build_id");if(r.lane_id!=="POST_MERGE_CLOSEOUT_ACCEPTANCE_REFERENCE_CONSISTENCY_CONTRACT")e.push("lane_id");if(r.owner_next_action!=="APPROVE_PREPARE_NEXT_SAFE_LANE_SCOUT_PACKET_AFTER_POST_MERGE_CLOSEOUT_ACCEPTANCE_REFERENCE_CONSISTENCY_CONTRACT_CLOSEOUT")e.push("owner_next_action");if(r.final_lane_status!=="LANE_CLOSED_READY_FOR_OWNER_ACCEPTANCE")e.push("final_lane_status");if(!sha.test(r.source_final_closeout_packet?.sha256??"")||r.source_final_closeout_packet.sha256!=="D7EA4C062B903FA1D76C2A9C5D8B92AE51D2E848494E96AD999D34B61FBA212A")e.push("source_final_closeout_packet.sha256");if(r.source_final_closeout_packet?.classification!=="POST_MERGE_CLOSEOUT_ACCEPTANCE_REFERENCE_CONSISTENCY_CONTRACT_FINAL_LANE_CLOSEOUT_PACKET_READY"||r.source_final_closeout_packet?.final_lane_status!=="LANE_CLOSED_READY_FOR_OWNER_ACCEPTANCE"||r.source_final_closeout_packet?.blocker_matrix!=="NO_BLOCKERS")e.push("source_final_closeout identity");if(r.replacement_pr?.number!==13||r.replacement_pr?.state!=="MERGED"||r.replacement_pr?.head_commit!=="3d95172d304ebfa619286b8cb3f28f7236a5d44e"||r.replacement_pr?.merge_commit!=="36aaeac837eee99c2117b2e8fada71517ebe0899")e.push("replacement_pr");if(r.superseded_pr?.number!==12||r.superseded_pr?.state!=="CLOSED"||r.superseded_pr?.head_commit!=="01099d1e20e957d11835cb7c75bfd06bf460f57b"||r.superseded_pr?.closed_at!=="2026-07-08T02:07:38Z"||r.superseded_pr?.merged_at!==null||r.superseded_pr?.merge_commit!==null||r.superseded_pr?.superseded_by_pr!==13)e.push("superseded_pr.close_link");if(r.remote_master!==r.replacement_pr?.merge_commit)e.push("remote_master");if(r.retained_branches?.branch_deletion_default!==false)e.push("retained_branches.branch_deletion_default");if(r.retained_branches?.dirty_pr12_branch?.head!=="01099d1e20e957d11835cb7c75bfd06bf460f57b"||r.retained_branches?.dirty_pr12_branch?.still_present!==true)e.push("retained_branches.dirty_pr12_branch");if(r.retained_branches?.clean_replacement_branch?.head!=="3d95172d304ebfa619286b8cb3f28f7236a5d44e"||r.retained_branches?.clean_replacement_branch?.still_present!==true)e.push("retained_branches.clean_replacement_branch");for(const [k,v] of Object.entries(r.safety_boundary??{}))if(v!==false)e.push(`safety.${k}`);return e;}
test("schema pins strict replacement closeout identity",()=>{const s=json(paths.schema);assert.equal(s.additionalProperties,false);assert.equal(s.properties.replacement_pr.properties.number.const,13);assert.equal(s.properties.superseded_pr.properties.number.const,12);assert.equal(s.properties.retained_branches.properties.branch_deletion_default.const,false)});
test("complete closeout chain passes",()=>assert.deepEqual(validate(json(paths.valid)),[]));
function mutated(p){const r=structuredClone(json(paths.valid));const m=json(p);const parts=m.path.split(".");let x=r;for(const part of parts.slice(0,-1))x=x[part];if(m.remove)delete x[parts.at(-1)];else x[parts.at(-1)]=m.value;return r;}
test("missing PR #12 close link fails closed",()=>assert.ok(validate(mutated(paths.missing)).some(x=>x.includes("superseded_pr.close_link"))));
test("branch deletion as default fails closed",()=>assert.ok(validate(mutated(paths.branch)).some(x=>x.includes("branch_deletion_default"))));
test("docs prohibit branch deletion and runtime authorization",()=>{const d=read(paths.doc);assert.match(d,/Branch deletion is never a default closeout action/);assert.match(d,/READY is not GO/)});
test("exact new file set is bounded",()=>assert.equal(Object.values(paths).length,6));
